### PR TITLE
Collapse ranges ameliorations

### PR DESCRIPTION
**Pull request by Patrikios**
Hi Argonaut,

I just came back to this repo after some time, looked into the package state as it wasnt developed in 2 years time.

I think the package still has a solid value proposition and if you agree I would like to contribute. I think my git-fu should be strong enough now.

Before I come up with features, I am looking into the current state and come up with non-critical amelioration in R code, for the function 'collapse_ranges'.

Take a look. Comments in the code will tell you as well more + the commit message.

Hope we can collaborate in free time.

Cheers.

Patrik

### CODE REVIEW

**Comment by arg0naut91** [comment]
Thanks Patrik for the improvements, looks all fine to me, also build seems to be a success. Sorry for not getting back earlier, wanted to run the code on some private use cases just to be 100% (likely unnecessary though, probably overdoing it). 

I'll make few checks over the course of this month and submit to CRAN. Given that you already made substantial indirect contribution with Rcpp suggestion and are now actively contributing, I will add you as author.

Feel free to push other modifications. Happy to hear if you've some suggestions about new functions / features. I've had a bit less time lately for active developments here, but am still interested in further improving / enriching the package.

**Comment by Patrikios** [comment]
No problem Aljaz,
As said, nice package worth the while. 

Indeed builds fine, however beaware after the last commit the check is stopped by some funny error. Saying some .so linking did not work. 
Will take a look later.

**Comment by Patrikios** [comment]
Hi again.

I tested again with my last commit, there is a compilation problem that I
did not see before 2 months when I worked on them.

Then I checked out your last commit:
[image: grafik.png]
and tested against it -> with the same result as for my commits:

==> Rcpp::compileAttributes()
* Updated R/RcppExports.R
==> devtools::test()
ℹ Loading neatRanges
Fehler in dyn.load(dll_copy_file) :
  kann shared object
'/tmp/Rtmpd4VgPR/pkgload31221c4604b4/neatRanges.so' nicht laden:
  /tmp/Rtmpd4VgPR/pkgload31221c4604b4/neatRanges.so: Ungültiger ELF-Header
Ruft auf: <Anonymous> ... <Anonymous> -> load_dll -> library.dynam2 -> dyn.load
Ausführung angehalten
Exited with status 1.


I am on R4.1.3,  Fedora 35.

It might be just my PC - had funny issues with some software components
overall on fedora (but still loving it).

Can u have  look if check() and test() all works fine and nice on your
machine?

Wishes
Patrik

**Comment by arg0naut91** [comment]
I had a look and didn't have issues with check/test. Perhaps this is a devtools issue, or there are some inconsistencies with softwares you're using (e.g. RTools not updated according to R version, not using the standard folder for it (e.g. C:\RTools40), and similar)?

I investigated a bit further and it seems there are issues (i.e. #22) with Rcpp-related parts of the code that are only flagged within certain distributions - basically Debian/Fedora using clang (as shown [here](https://cran.r-project.org/web/checks/check_results_neatRanges.html)). It should be fixed now in latest commit - perhaps that could also help?

Otherwise the build seems to be a success regardless of which distribution I test on e.g. [r-hub](https://builder.r-hub.io/). It's tricky though as I cannot replicate the #22 warnings mentioned in CRAN checks anywhere; it'll likely be only after CRAN submission that we'll see whether it's fixed.

I did some other very small changes - removed Travis service for now (as it was migrated), and adjusted a bit the documentation.

**Pull request merged**
